sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 6.4.0
install:
 - wget https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
 - unzip BrowserStackLocal-linux-x64.zip
 - ./BrowserStackLocal -v -onlyAutomate -forcelocal $BROWSERSTACK_ACCESS_KEY &
 - sleep 3
 - npm install
before_script:
  - npm prune
  - npm run start-ui-test-server &
script:
  - npm run lint
  - npm run test
  - npm run build
  - npm run test-ui
after_success:
  - npm run semantic-release
branches:
  only:
    - master
